Mayor Fixes
TOS-VRC/Role-Board pull request #9
Opened 2024-06-23 18:04 UTC by Deantwo

### Mayor
- Slight changes to abilities:
> Choose to reveal yourself as the Mayor at any point during the day. This is done using the pop-up menu during any of the day phases. This will reveal your role to everyone.
> 
> If you are unable to use the pop-up menu, you can also reveal by saying 'I reveal as Mayor' to the Host, but say it exactly. You can still reveal even if you are Blackmailed by a Blackmailer.
- Slight changes to attributes:
> Once revealed, your role be revealed for everyone to see and your vote counts as three during accusations and voting phases. but you can no longer be healed by a Doctor and you are no longer allowed to use whispers.
- Added note to additional note:
> As the Mayor, you are able to win a one-verse-one with any roles during the accusation phase, since you can break the voting tie.

2024-06-23 18:06 UTC, Deantwo commented
<https://town-of-salem.fandom.com/wiki/Mayor_(ToS)>
> **Mechanics**
> * You are the only role who can win in a 1 vs. 1 against Pestilence, due to you having your vote count as three and, therefore, being able to lynch them.
>   * Furthermore, you are also able to win a 1 vs. 1 against any other evil role as well, provided they don't kill you first.

2024-06-24 14:43 UTC, Miner28 requested changes
Missing will

2024-06-24 14:54 UTC, Deantwo commented
> Missing will

"Once revealed, your vote counts as three" is correct. Unless you have a better way of writing it. I guess you didn't notice I changed the whole sentence?

2024-06-24 14:57 UTC, Miner28 approved these changes

2024-06-24 14:58 UTC, merged